uploads = []
generated = []

[[outputs]]
id = "lIcEzOdnqzzsuX84mN9mW"
uri = "file://premium_tools_combined_fixed.zip"
type = "unspecified"
title = "premium_tools_v4 — Mass Comment + Web UI + No Key Lock"
